### ISSUE TITLE
RFC proposal: build system

### ISSUE THREAD

**Issue by mseri** [shtukas/Gaia#1]
To avoid compilation and compatibility problems with the libraries, have a uniform environment and have a system that works nicely also on El Capitan I suggest using [stack](https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md) and the latest build resolver: [lts-3.13](https://www.stackage.org/lts-3.13).

It's quite easy and much less painful than going directly with cabal.

For the guide look [here](https://github.com/commercialhaskell/stack/blob/release/doc/GUIDE.md)

**Comment by shtukas** [comment]
Done. See latest commit. Cheers,
