### ISSUE TITLE
Use safe and multiplatform interfaces for file access

### ISSUE THREAD

**Issue by mseri** [shtukas/Gaia#3]
I suggest to use the `filepath` package and its `System.FilePath` (https://hackage.haskell.org/package/filepath) module for the purpose. This abstracts away systems differences and would make the code safer (and multiplatform)

**Comment by shtukas** [comment]
Done!

**Comment by mseri** [comment]
Woo!! I’ve just arrived back home :) time to update again. From the little I’ve seen it looks great!

M
