### ISSUE TITLE
Move Types together

### ISSUE THREAD

**Issue by mseri** [shtukas/Gaia#4]
I suggest we move filesystem related types (and type alias) to a separate `Gaia.FS.Types` module, the same for logic or structure related types like the one used for the directives in e.g. `Gaia.Types`.

**Comment by mseri** [comment]
For example the I could already use the FilePath type [here](https://github.com/shutkas/Gaia/blob/master/src/Directives.hs#L91) and this would document the function more explicitly.

Same for Xcache, some Strings there should be FilePath.

In addition, if we agree on issue #3 a simple change to the type module would reflect automatically to the other modules (pointing out if something need a fix).

**Comment by shtukas** [comment]
No problem, do that. Just pull from me before you start. Cheers,

**Comment by mseri** [comment]
Ok, I proceed

**Comment by mseri** [comment]
Last merge closes this
